import type { FlowDefinition } from "@/lib/flows/types";

export const ONBOARDING_FLOW_DEFINITION: FlowDefinition = {
  type: "onboarding",
  initialStep: "month_ref",
  questions: [
    {
      key: "month_ref",
      fieldPath: "_meta.month_ref",
      parser: "month_ref",
      required: true,
      prompt: (context) =>
        [
          "Ola! Tudo bem? Preciso te fazer algumas perguntas importantes.",
          "Essas respostas vao ser a base do seu sistema e do seu diagnostico mensal.",
          `Posso usar o mes ${formatMonthRef(context.suggestedMonthRef)} como referencia?`,
          "Responda 'sim' para confirmar ou envie outro mes no formato MM/AAAA.",
        ].join("\n"),
    },
    {
      key: "a_tipo_posto",
      fieldPath: "a_tipo_posto",
      parser: "operation_type",
      required: true,
      coreRequired: true,
      prompt: "a) Seu posto e Urbano, Rodoviario ou Misto?",
    },
    {
      key: "b_volume_diesel_l",
      fieldPath: "b_volume_diesel_l",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "b) Qual o volume total de diesel vendido no mes (S10, S500 e aditivados), em litros?",
    },
    {
      key: "c_volume_otto_l",
      fieldPath: "c_volume_otto_l",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt:
        "c) Qual o volume total de gasolina e etanol vendidos no mes (GC, GA, Etanol comum e Etanol aditivado), em litros?",
    },
    {
      key: "d_gnv_m3",
      fieldPath: "d_gnv_m3",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "d) Qual a metragem cubica de GNV vendida no mes (m3)?",
    },
    {
      key: "e_volume_otto_aditivado_l",
      fieldPath: "e_volume_otto_aditivado_l",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt:
        "e) Qual o volume de gasolina e etanol aditivados vendidos no mes (GA + Etanol aditivado), em litros?",
    },
    {
      key: "f_volume_diesel_aditivado_l",
      fieldPath: "f_volume_diesel_aditivado_l",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "f) Qual o volume de diesel aditivado vendido no mes (S10 + S500 aditivados), em litros?",
    },
    {
      key: "g_qtd_frentistas",
      fieldPath: "g_qtd_frentistas",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "g) Quantos frentistas voce possui?",
    },
    {
      key: "h_turno",
      fieldPath: "h_turno",
      parser: "shift",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "h) Qual o turno de trabalho dos frentistas? (12x36 ou 8h)",
    },
    {
      key: "i_horario_funcionamento",
      fieldPath: "i_horario_funcionamento",
      parser: "text",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "i) Qual seu horario de funcionamento?",
    },
    {
      key: "j_faturamento_pista",
      fieldPath: "j_faturamento_pista",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt:
        "j) Qual valor (faturamento) de produtos vendidos na pista (exceto combustiveis), em R$ no mes?",
    },
    {
      key: "l_faturamento_troca_oleo",
      fieldPath: "l_faturamento_troca_oleo",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "l) Qual valor de produtos vendidos na troca de oleo (somente na troca), em R$ no mes?",
    },
    {
      key: "m_margem_media_pista_pct",
      fieldPath: "m_margem_media_pista_pct",
      parser: "percentage_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt:
        [
          "m) Qual a margem media dos produtos vendidos na pista, em %?",
          "Use margem de lucro (nao markup).",
          "Margem = (preco de venda - preco de custo) / preco de venda.",
          "Markup = (preco de venda - preco de custo) / preco de custo.",
          "A margem pedida aqui e bruta (sem frete, impostos e despesas).",
        ].join("\n"),
    },
    {
      key: "n_margem_media_troca_pct",
      fieldPath: "n_margem_media_troca_pct",
      parser: "percentage_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt:
        [
          "n) Qual a margem media dos produtos vendidos na troca de oleo, em %?",
          "Use margem de lucro (nao markup).",
          "Margem = (preco de venda - preco de custo) / preco de venda.",
          "A margem pedida aqui e bruta (sem frete, impostos e despesas).",
        ].join("\n"),
    },
    {
      key: "o_trocas_oleo_por_dia",
      fieldPath: "o_trocas_oleo_por_dia",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "o) Quantas trocas de oleo sao feitas por dia?",
    },
    {
      key: "p_faturamento_conveniencia",
      fieldPath: "p_faturamento_conveniencia",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "p) Qual faturamento mensal da loja de conveniencia, em R$?",
    },
    {
      key: "q_funcionarios_conveniencia",
      fieldPath: "q_funcionarios_conveniencia",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "q) Quantos funcionarios na loja de conveniencia?",
    },
    {
      key: "r_food_service_faturamento",
      fieldPath: "r_food_service_faturamento",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "r) Qual faturamento da linha de food service da conveniencia, em R$ no mes?",
    },
    {
      key: "s_bebidas_faturamento",
      fieldPath: "s_bebidas_faturamento",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "s) Qual faturamento da linha de bebidas da conveniencia, em R$ no mes?",
    },
    {
      key: "t_mercearia_faturamento",
      fieldPath: "t_mercearia_faturamento",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "t) Qual faturamento da linha de mercearia da conveniencia, em R$ no mes?",
    },
    {
      key: "u_bomboniere_tabacaria_faturamento",
      fieldPath: "u_bomboniere_tabacaria_faturamento",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "u) Qual faturamento da linha de bomboniere e tabacaria da conveniencia, em R$ no mes?",
    },
    {
      key: "v_diff_custo_aditivada_r_l",
      fieldPath: "v_diff_custo_aditivada_r_l",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt:
        "v) Qual a diferenca de custo dos combustiveis aditivados em relacao aos comuns (R$/L)?",
    },
    {
      key: "x_precos_venda_ga",
      fieldPath: "x_precos_venda.ga",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.1) Preco de venda da Gasolina Aditivada (GA), em R$/L?",
    },
    {
      key: "x_precos_venda_gc",
      fieldPath: "x_precos_venda.gc",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.2) Preco de venda da Gasolina Comum (GC), em R$/L?",
    },
    {
      key: "x_precos_venda_etanol_comum",
      fieldPath: "x_precos_venda.etanol_comum",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.3) Preco de venda do Etanol comum, em R$/L?",
    },
    {
      key: "x_precos_venda_etanol_aditivado",
      fieldPath: "x_precos_venda.etanol_aditivado",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.4) Preco de venda do Etanol aditivado, em R$/L?",
    },
    {
      key: "x_precos_venda_s10",
      fieldPath: "x_precos_venda.s10",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.5) Preco de venda do Diesel S10, em R$/L?",
    },
    {
      key: "x_precos_venda_s500",
      fieldPath: "x_precos_venda.s500",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.6) Preco de venda do Diesel S500, em R$/L?",
    },
    {
      key: "x_precos_venda_s10_aditivado",
      fieldPath: "x_precos_venda.s10_aditivado",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.7) Preco de venda do Diesel S10 aditivado, em R$/L?",
    },
    {
      key: "x_precos_venda_s500_aditivado",
      fieldPath: "x_precos_venda.s500_aditivado",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "x.8) Preco de venda do Diesel S500 aditivado, em R$/L?",
    },
    {
      key: "x_precos_venda_gasolina_premium",
      fieldPath: "x_precos_venda.gasolina_premium",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "x.9) Preco de venda da Gasolina Premium, em R$/L? (pode pular)",
    },
    {
      key: "x_precos_venda_gnv",
      fieldPath: "x_precos_venda.gnv",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "x.10) Preco de venda do GNV, em R$/m3? (pode pular)",
    },
    {
      key: "y_oleo_litros_vendidos",
      fieldPath: "y_oleo_litros_vendidos",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "y) Quantos litros de oleo lubrificante foram vendidos no mes (pista + troca)?",
    },
    {
      key: "z_qtd_trocadores_oleo",
      fieldPath: "z_qtd_trocadores_oleo",
      parser: "number_br",
      required: false,
      allowSkip: true,
      allowKeep: true,
      prompt: "z) Posto possui trocador de oleo? Quantos?",
    },
    {
      key: "aa_qtd_abastecimentos_mes",
      fieldPath: "aa_qtd_abastecimentos_mes",
      parser: "number_br",
      required: true,
      coreRequired: true,
      allowKeep: true,
      prompt: "aa) Quantos abastecimentos foram feitos no mes?",
    },
  ],
};

export function getOnboardingCoreKeys(): string[] {
  return ONBOARDING_FLOW_DEFINITION.questions.filter((item) => item.coreRequired).map((item) => item.key);
}

function formatMonthRef(monthRef?: string): string {
  if (!monthRef) return "(mes anterior)";
  const [year, month] = monthRef.split("-");
  return `${month}/${year}`;
}

